added coroutines
Skatteetaten/cantus pull request #12
Opened 2019-03-04 15:51 UTC by kris456

2019-03-08 11:16 UTC, kris456 commented on src/main/resources/application.yaml
> +    max-http-header-size: 200000
Denne må være her for å støtte litt lengre query parametre. Noen som har innspill på hvor høy den burde være? nå støtter den å hente alle manifestene til Boober.

2019-03-08 12:32 UTC, bjartek requested changes

2019-03-08 12:32 UTC, bjartek commented on build.gradle
> +      "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.1",
1.1.1?

2019-03-08 12:32 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +        val context = newFixedThreadPoolContext(6, "cantus")
Denne trådpoolen bør kanskje være et config parameter?

2019-03-08 12:54 UTC, kris456 commented on build.gradle
> +      "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.1",
fikset :+1:

2019-03-08 13:33 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +        val context = newFixedThreadPoolContext(6, "cantus")
Enig, fikset nå :+1:

2019-03-11 09:58 UTC, bjartek approved these changes

2019-03-11 12:47 UTC, merged