Feature/aos 3121 bytte av response format til hal hypermedia format
Skatteetaten/cantus pull request #3
Opened 2019-01-18 15:34 UTC by kris456

Gjenstår refaktorering og få testene til å fungere

2019-01-21 07:11 UTC, bjartek commented
Idag trekkes det inn et hal bibliotek her, men det er ikke under aktiv utvikling. Skulle vi laget et eget lite aurora-kotlin-utils bibliotek med kode som vi gjenbruker veldig mye? Alternativt skal vi lage mange små?

Et bibliotek med exceptions og responseklasser og litt extension methods kanskje?

- https://github.com/davidsowerby/hal-kotlin

2019-01-21 07:15 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            return ImageManifestDto(dockerDigest = "", dockerVersion = "")
Mister vi ikke noe informasjon her? Burde vi her hive en exception?

2019-01-21 11:43 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            return ImageManifestDto(dockerDigest = "", dockerVersion = "")
Det blir nå hivet en exception av type SourceSystemException som blir tatt hånd om av Error handleren. Responsen som kommer til kalleren er da et response av type HAL format med exception inni denne.

2019-01-22 07:28 UTC, jarlehansen requested changes

2019-01-22 07:28 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +    companion object {
Denne er både en @Component og har companion object. Virker litt unødvendig for meg, er det en grunn til det?

2019-01-22 07:28 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/ErrorHandler.kt
> +        println(it.message)
litt debugging kode som henger igjen :)

2019-01-22 07:28 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            sourceSystem = url
Source system er ment for å vise system navnet der den opprinnelige feilen skjer, kanskje det burde stå "docker registry" her?

2019-01-22 07:28 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryControllerTest.kt
> +        `when`(dockerService.getImageTags(any(), any(), anyOrNull())).thenThrow(
Siden when er et reservert ord i kotlin så må man bruke `
Jeg foretrekker heller å bruke BDDMockito.given()

2019-01-22 08:12 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +    companion object {
Det var meg som skrev dette og jeg tror bare jeg har surret litt. Hva er det vi gjør andre steder? Så lenge det er likt som i mokey og de andre er det samme for meg hva vi velger.

2019-01-22 08:13 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            sourceSystem = url
Poenget her er at vi har flere docker registies vi går mot. Vi må ha en måte å skille dem på. Hvis vi får masse feil fra interne registry men ikke eksterne?

2019-01-22 08:16 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryControllerTest.kt
> +        `when`(dockerService.getImageTags(any(), any(), anyOrNull())).thenThrow(
Så when i java er det samme som given i kotlin? :) Takk!

2019-01-22 08:33 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/ErrorHandler.kt
> +        println(it.message)
Se der har det sneket seg med en sånn :) Fikser det!

2019-01-22 09:04 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +    companion object {
@Component er nok å foretrekke, pga enklere mocking

2019-01-22 09:04 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            sourceSystem = url
Godt poeng, bruk det som gir oss mest verdi når vi trenger å feilsøke. hvis det er url'en så bare behold det.

2019-01-22 09:06 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryControllerTest.kt
> +        `when`(dockerService.getImageTags(any(), any(), anyOrNull())).thenThrow(
Nei, ikke helt. "when" i Kotlin er et reservert ord, det er det ikke i Java. Så når man skal lage en funksjon i Kotlin som heter when så må den skrives `when` sånn. Så får å unngå denne syntaxen, så foretrekker jeg å bruke given. Given gjør det samme som when i mockito, bare at det er BDD måten å sette det opp på.

2019-01-22 09:46 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +    companion object {
Companion object er fjernet og bean er laget for ImageTagResourceAssembler

2019-01-22 09:46 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryControllerTest.kt
> +        `when`(dockerService.getImageTags(any(), any(), anyOrNull())).thenThrow(
Jeg skjønner :) Fikset nå.

2019-01-22 09:48 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerRegistryService.kt
> +            sourceSystem = url
Kan det her være lurt å sette på en prefix for urlen eller vet man at det er Docker registry ut ifra alle urlene som kan brukes?

2019-01-22 11:28 UTC, bjartek approved these changes

2019-01-22 11:46 UTC, merged