feature/AOS-3695-detekt
Skatteetaten/cantus pull request #33
Opened 2019-11-15 08:10 UTC by kris456

2019-11-20 12:12 UTC, bjartek requested changes

2019-11-20 12:12 UTC, bjartek commented on build.gradle.kts
> +sonarqube {
Denne bør vi legge inn i vår plugin hvis vi har sonarplugin aktivert.

2019-11-20 12:12 UTC, bjartek commented on src/test/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClientTest.kt
> +                .contains("Only v2 manifest is supported. contentType=")
Hvorfor forsvant content type herfra?

2019-11-20 12:12 UTC, bjartek commented on src/test/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClientTest.kt
> +                .matches(Regex(".*cause=Unauthorized lastError=401 Unauthorized from HEAD .* operation=BLOB_EXIST.*"))
Jeg vet ikke helt om jeg synes regex er bedre her.

2019-11-20 12:16 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClientTest.kt
> +                .matches(Regex(".*cause=Unauthorized lastError=401 Unauthorized from HEAD .* operation=BLOB_EXIST.*"))
På grunn av en oppdatert dependency vil den tidligere løsningen feile. Det har kommet ekstra informasjon mellom Unauthorized og operation=BLOB_EXIST. Denne ekstra informasjonen er en url som genereres.

2019-11-20 12:16 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClientTest.kt
> +                .contains("Only v2 manifest is supported. contentType=")
Det er en glipp. Tar den tilbake

2019-11-20 14:35 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +            val status = if (e is IllegalArgumentException) {
Dette er en litt uvanlig konstruksjon. Her catches Exception som eksplisitt kastes i try-blokken, og man ender da opp med det som heter Exceptions for control flow (som er et anit-pattern). For å unngå dette kan du bruke en en if-return guard clause istedenfor require-statementene.

2019-11-20 14:35 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClient.kt
> +        val manifestResponse: ManifestResponse = to.createRequest(
I utgangspunktet bør ikke DTO-objektene ha et forhold til http-klient. Her mener jeg at ansvaret bør byttes om; f.eks. kan createRequest være en extension function på WebClient eller en generell utility-metode der hvor disse requestene lages, som tar ImageRepoCommand som parameter.

2019-11-20 14:35 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClient.kt
>                  headers.contentLength = 0L
Akkurat denne fortjener en liten kommentar. Hva er det som gjør at man må sette contentLength til 0 her?

2019-11-20 14:35 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClient.kt
>              .performBodyAndHeader(imageRepoCommand)
Trengs imageRepoCommand som parameter her?

2019-11-20 14:35 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClient.kt
>              .performBodyAndHeader(to)
Ser ikke ut til at to-parameteren brukes?

2019-11-21 07:20 UTC, bjartek commented on src/test/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClientTest.kt
> +                .matches(Regex(".*cause=Unauthorized lastError=401 Unauthorized from HEAD .* operation=BLOB_EXIST.*"))
Da synes jeg vi bare bør teste på noe annet som ikke krever at vi bruker Regex. Hvis det er viktig her at man tester både på 401 og på operation så kan man ha 2 contains kall?

2019-11-21 07:22 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/service/DockerHttpClient.kt
>                  headers.contentLength = 0L
Det er et godt spm, men det er ikke noe som er endret i denne PR. Så er det rett plass å ta det?

Svar: Hvis jeg husker rett fra artikkelen som denne koden er inspirert fra så krever docker sitt api at content length er satt og klienten gjør det ikke automatisk hvis man ikke har body.

2019-11-21 07:22 UTC, bjartek requested changes
La inn et par kommentarer til

2019-11-21 12:39 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> +            val status = if (e is IllegalArgumentException) {
Ser at det er litt dumt. Forandrer det

2019-11-27 08:13 UTC, bjartek approved these changes

2020-08-25 06:36 UTC, closed without merging