Feature/aos 4616 oppgradere avhengigheter
Skatteetaten/cantus pull request #35
Opened 2020-06-14 18:52 UTC by kris456

2020-06-18 12:33 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> -            // TODO: the http error in here is an authentication error then we should perhaps throw another status?
Regner med denne er gammel?

2020-06-18 12:44 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/DockerRegistryController.kt
> -            // TODO: the http error in here is an authentication error then we should perhaps throw another status?
Ja

2020-06-19 09:26 UTC, jarlehansen requested changes

2020-06-19 09:26 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/ErrorHandler.kt
> +    times = RETRY_MAX_ATTEMPTS,
Kan det være feil som gjør at vi ikke ønsker å retrye?
Hva om den får 401 response feks?

2020-07-06 08:14 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/cantus/controller/ErrorHandler.kt
> +    times = RETRY_MAX_ATTEMPTS,
fikset i: https://github.com/Skatteetaten/cantus/pull/35/commits/d9f711a34c0b41bb1c5bcd96f9a39914e89b896a

2020-07-06 10:50 UTC, jarlehansen approved these changes

2020-07-09 06:32 UTC, martinrodland approved these changes

2020-08-17 12:31 UTC, bjartek approved these changes
Upgrade gradle then OK.

2020-08-25 14:43 UTC, merged